# node 12.18.0
#
# yarn 1.2.44

FROM node:12.18.0-buster-slim
LABEL maintainer="Soumik Mukherjee <me@soumikmukherjee.dev>"
RUN mkdir /home/node/app/ && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node package.json ./
COPY --chown=node:node yarn.lock ./
USER node
RUN yarn

COPY --chown=node:node src ./src/
COPY --chown=node:node babel.config.js .
COPY --chown=node:node .env .

RUN yarn dev:build
EXPOSE 8080
EXPOSE 9339
# CMD ["yarn", "start"]
ENTRYPOINT ["yarn", "dev:debug"]